### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "password12345678"
}

### Find a particular user by id
GET http://localhost:3000/auth/4

### Find all users with a particular email
GET http://localhost:3000/auth?email=test@gmail.com

### Delete a user by id
DELETE http://localhost:3000/auth/62144124

### Update a user by id
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
    "email": "updated2@gmail.com"
}