### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "kitoy3@gmail.com",
    "password": "password12345678"
}

### Sign in existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "kitoy2@gmail.com",
    "password": "password12345678"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out the currently signed in user
POST http://localhost:3000/auth/signout

### Find a particular user by id
GET http://localhost:3000/auth/4

### Find all users with a particular email
GET http://localhost:3000/auth?email=test@gmail.com

### Delete a user by id
DELETE http://localhost:3000/auth/62144124

### Update a user by id
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
    "email": "updated2@gmail.com"
}

### Set a color in the session ###
GET http://localhost:3000/auth/colors/violet

### Get the color from the session ###
GET http://localhost:3000/auth/colors